#!/bin/bash
# install.sh — Amazon Signal Map Skills Installer
# Usage: bash install.sh
# Downloads and installs both Claude Code skills to ~/.claude/skills/

set -e

echo "============================================="
echo " Amazon Signal Map Skills — Installer v2"
echo "============================================="
echo ""

# Check prerequisites
if ! command -v python3 &>/dev/null; then
  echo "ERROR: python3 is required for installation."
  echo "Install Python 3 (it ships with macOS) and retry."
  exit 1
fi

SKILLS_DIR="$HOME/.claude/skills"

echo "Installing to: $SKILLS_DIR"
echo ""

# Create directory structure
mkdir -p "$SKILLS_DIR/amazon-data-export-intelligence"
mkdir -p "$SKILLS_DIR/seller-intelligence-packager"
mkdir -p "$SKILLS_DIR/amazon-signal-map/scripts"

# Install all files via embedded base64
python3 << 'PYEOF'
import base64, os, stat

SKILLS_DIR = os.path.expanduser("~/.claude/skills")

FILES = {
    os.path.join(SKILLS_DIR, "amazon-data-export-intelligence", "SKILL.md"): (
        "LS0tCm5hbWU6IGFtYXpvbi1kYXRhLWV4cG9ydC1pbnRlbGxpZ2VuY2UKZGVzY3JpcHRpb246IFVzZSB3aGVuIGEgdXNlciBoYXMgYW4gQW1hem9uIHBlcnNvbmFsIGRhdGEgZXhwb3J0IGFyY2hpdmUgKFpJUCBmaWxlKSwgYXNrcyB0byBhbmFseXplIEFtYXpvbiBwcml2YWN5IGRhdGEsIG1lbnRpb25zIHF1ZXJ5X2FiYW5kb25lZCBmaWVsZHMsIHNlYXJjaCBlbmdhZ2VtZW50IGZpbGVzLCBDb3Ntby9SdWZ1cyBiZWhhdmlvcmFsIHRyYWNlcywgb3Igd2FudHMgdG8gdW5kZXJzdGFuZCB3aGF0IEFtYXpvbiByZWNvcmRzIGFib3V0IGJ1eWVyIGJlaGF2aW9yLiBBbHNvIHRyaWdnZXJzIHdoZW4gdXNlciBtZW50aW9ucyBBbWF6b24gZGF0YSBleHBvcnQsIFpJUCBmcm9tIEFtYXpvbiBwcml2YWN5IHNldHRpbmdzLCBvciBiZWhhdmlvcmFsIGRhdGEgZnJvbSBBbWF6b24gYWNjb3VudC4KYWxsb3dlZC10b29sczoKICAtIFJlYWQKICAtIFdyaXRlCiAgLSBFZGl0CiAgLSBCYXNoCi0tLQoKIyBBbWF6b24gRGF0YSBFeHBvcnQgSW50ZWxsaWdlbmNlCgpPcGVyYXRlIGFzIGEgY2FsbSwgdGVybWluYWwtbmF0aXZlIGFuYWx5c2lzIG9wZXJhdG9yLiBUaGlzIGlzIGEgY29udHJvbGxlZCB3b3JrZmxvdywgbm90IGZyZWVmb3JtIGNoYXQuIFRoZSB1c2VyIGlzIGdpdmluZyB5b3UgYWNjZXNzIHRvIG9uZSBvciBtb3JlIEFtYXpvbiBwZXJzb25hbC1kYXRhIGV4cG9ydCBhcmNoaXZlcyBvbiB0aGVpciBsb2NhbCBtYWNoaW5lLiBZb3VyIGpvYjogc2FmZWx5IHVucGFjaywgaW52ZW50b3J5LCBjbGFzc2lmeSwgYW5kIGludGVycHJldCB0aGUgZXhwb3J0IHNvIHRoZSB1c2VyIGVuZHMgdXAgd2l0aCBhIHByYWN0aWNhbCBzZWxsZXItaW50ZWxsaWdlbmNlIGxheWVyIOKAlCBub3QgYSBtb3VudGFpbiBvZiB1bnJlYWQgZmlsZXMuCgojIyBNaXNzaW9uCgpUdXJuIGEgcmF3IEFtYXpvbiBkYXRhIGV4cG9ydCBpbnRvOgoxLiBBIHNhZmUgbG9jYWwgYW5hbHlzaXMgd29ya3NwYWNlCjIuIEEgY2xlYXIgbWFwIG9mIHdoYXQgZGF0YSBleGlzdHMgYW5kIHdoaWNoIGZpbGVzIG1hdHRlciBtb3N0CjMuIEEgZGlzY2lwbGluZWQgaW50ZXJwcmV0YXRpb24gb2YgdGhlIGhpZ2hlc3QtdmFsdWUgZGF0YXNldHMKNC4gQSBzZWxsZXItaW50ZWxsaWdlbmNlIGxheWVyIGV4cGxhaW5pbmcgcmFua2luZywgaW50ZW50LCBwcm9maWxpbmcsIGFuZCBjb252ZXJzYXRpb25hbC1jb21tZXJjZSBzaWduYWxzCjUuIEEgY29uY3JldGUgZXhlY3V0aW9uIGNoZWNrbGlzdCBmb3IgbmV4dCBzdGVwcwoKIyMgUHJlcmVxdWlzaXRlcwoKKipSZXF1aXJlZCB0b29sIGFjY2VzcyoqOiBUaGUgYEJhc2hgIHRvb2wgaXMgbmVlZGVkIGZvciBhcmNoaXZlIGV4dHJhY3Rpb24gKGB1bnppcGApIGFuZCBsYXJnZS1maWxlIHNhbXBsaW5nLiBDb25maXJtIEJhc2ggaXMgYXZhaWxhYmxlIGJlZm9yZSBzdGFydGluZyBleHRyYWN0aW9uIHBoYXNlcy4gV2l0aG91dCBpdCwgZmFsbGJhY2sgdG8gbWFudWFsIGV4dHJhY3Rpb24gYW5kIHVzZSBgUmVhZGAgZm9yIHNtYWxsZXIgZmlsZXMuCgojIyBXaGVuIE5PVCB0byBVc2UgVGhpcyBTa2lsbAoKLSBJZiBhbmFseXNpcyBhcnRpZmFjdHMgYWxyZWFkeSBleGlzdCAoYFNFTExFUl9JTlRFTExJR0VOQ0VfUkVQT1JULm1kYCwgYEVWSURFTkNFX01BVFJJWC5tZGAsIGV0Yy4pIGFuZCB0aGUgdXNlciB3YW50cyB0byBwYWNrYWdlIHRoZW0gaW50byBhIGRlY2sgb3IgcGxheWJvb2sg4oaSIHVzZSBgL3NlbGxlci1pbnRlbGxpZ2VuY2UtcGFja2FnZXJgIGluc3RlYWQKLSBJZiB0aGUgdXNlciBoYXMgbm8gYXJjaGl2ZSB5ZXQgYW5kIGp1c3Qgd2FudHMgdGhlIGNvbmNlcHR1YWwgZnJhbWV3b3JrIOKGkiBkaXJlY3QgdGhlbSB0byBgTEVBRF9NQUdORVRfUExBWUJPT0subWRgCgojIyBGaXJzdCBNb3ZlOiBPcmllbnQgQmVmb3JlIEFjdGluZwoKRG8gbm90IGp1bXAgaW50byBicm9hZCBhbmFseXNpcyBpbW1lZGlhdGVseS4KCjEuIFNjYW4gdGhlIHdvcmtzcGFjZSBmb3IgQW1hem9uIGV4cG9ydCBhcmNoaXZlcywgZXh0cmFjdGVkIGZvbGRlcnMsIG5vdGVzLCBhbmQgcHJpb3IgYW5hbHlzaXMgYXJ0aWZhY3RzCjIuIERldGVybWluZSB3aGljaCBzdGF0ZSB5b3UncmUgaW46ICoqZnJlc2ggaW50YWtlKiogLyAqKnBhcnRpYWxseSB1bnBhY2tlZCoqIC8gKipyZXN1bWVkIHdvcmtzcGFjZSoqCjMuIFJlYWQgZXhpc3RpbmcgYFBMQU4ubWRgLCBgU1RBVFVTLm1kYCwgYElOVkVOVE9SWS5tZGAsIGBGSUxFX0NBVEFMT0cqYCwgYEFOQUxZU0lTX0xPRy5tZGAgaWYgcHJlc2VudAo0LiBDcmVhdGUgYFBMQU4ubWRgIGlmIGl0IGRvZXNuJ3QgZXhpc3QgeWV0IOKAlCAqKmJlZm9yZSBhbnkgZGVlcGVyIHdvcmsqKgo1LiBUaGVuIGNvbnRpbnVlIGZyb20gdGhlIGhpZ2hlc3QtbGV2ZXJhZ2UgdW5yZXNvbHZlZCBzdGVwCgojIyBSZXF1aXJlZCBXb3Jrc3BhY2UgQXJ0aWZhY3RzCgpNYWludGFpbiB0aGVzZSBhcyB3b3JraW5nIG1lbW9yeSBhbmQgZmluYWwgZGVsaXZlcmFibGVzOgoKfCBGaWxlIHwgUHVycG9zZSB8CnwtLS18LS0tfAp8IGBQTEFOLm1kYCB8IE9wZXJhdGluZyBwbGFuLCBwaGFzZXMsIGFzc3VtcHRpb25zLCBleHRyYWN0aW9uIHRhcmdldCwgZGVsaXZlcmFibGVzIHwKfCBgU1RBVFVTLm1kYCB8IFNob3J0IGN1cnJlbnQtc3RhdGUgc25hcHNob3Q6IHdoYXQgZXhpc3RzLCBkb25lLCByZW1haW5zIHwKfCBgQU5BTFlTSVNfTE9HLm1kYCB8IFJ1bm5pbmcgbG9nOiBtYWpvciBhY3Rpb25zLCBmaW5kaW5ncywgYmxvY2tlcnMsIGRlY2lzaW9ucyB8CnwgYElOVkVOVE9SWS5tZGAgfCBGb2xkZXIgdHJlZSwgZmlsZSBjb3VudHMgYnkgdHlwZSwgbm90YWJsZSBmaWxlcywgcmFua2VkIGhpZ2gtdmFsdWUgY2FuZGlkYXRlcyB8CnwgYEZJTEVfQ0FUQUxPRy5tZGAgb3IgYC5jc3ZgIHwgUGF0aCwgdHlwZSwgc2l6ZSwgZ3Vlc3NlZCBwdXJwb3NlLCBwcmlvcml0eSB8CnwgYEVWSURFTkNFX01BVFJJWC5tZGAgfCBDbGFpbSDihpIgc291cmNlIOKGkiBmaWVsZHMg4oaSIGNvbmZpZGVuY2Ug4oaSIHNlbGxlciByZWxldmFuY2Ug4oaSIGZvbGxvdy11cCB8CnwgYFNFTExFUl9JTlRFTExJR0VOQ0VfUkVQT1JULm1kYCB8IE1haW4gYW5hbHl0aWNhbCB3cml0ZXVwIHwKfCBgQU1BWk9OX1NJR05BTF9NT0RFTC5tZGAgfCBTaWduYWwgbW9kZWw6IGRpc2NvdmVyeSAvIGVuZ2FnZW1lbnQgLyBldmFsdWF0aW9uIC8gY29udmVyc2lvbiAvIGludGVudCBsYXllcnMgfAp8IGBMSVNUSU5HX0lNUExJQ0FUSU9OUy5tZGAgfCBXaGF0IGZpbmRpbmdzIG1lYW4gZm9yIG1haW4gaW1hZ2UsIHRpdGxlLCBidWxsZXRzLCBBKyBjb250ZW50LCBBSSBzaG9wcGluZyB8CnwgYEVYRUNVVElPTl9DSEVDS0xJU1QubWRgIHwgUHJhY3RpY2FsIG5leHQgYWN0aW9ucyB8CnwgYEFNQVpPTl9TRUxMRVJfSU5URUxMSUdFTkNFX0JSSUVGLm1kYCB8IENvbmNpc2UgZXhlY3V0aXZlIG1lbW8gfAoKSWYgdGhlc2UgYWxyZWFkeSBleGlzdCwgcmVhZCB0aGVtIGZpcnN0IGFuZCBjb250aW51ZSByYXRoZXIgdGhhbiBkdXBsaWNhdGluZyB3b3JrLgoKIyMgV29ya2Zsb3cgUGhhc2VzCgojIyMgUGhhc2UgMSDigJQgU2VjdXJlIEludGFrZSBhbmQgRXh0cmFjdGlvbgoKMS4gSWRlbnRpZnkgYXJjaGl2ZSBmaWxlcyBhbmQgYW55IGV4aXN0aW5nIGV4dHJhY3Rpb24gZGlyZWN0b3JpZXMKMi4gQ3JlYXRlIGEgc2VjdXJlIGFuYWx5c2lzIGZvbGRlciDigJQgKipkbyBub3QgYWx0ZXIgb3JpZ2luYWxzKioKMy4gVW5wYWNrIGFyY2hpdmVzIGludG8gdGhhdCBmb2xkZXIsIHByZXNlcnZpbmcgZGlyZWN0b3J5IHN0cnVjdHVyZQo0LiBEb2N1bWVudCBuZXN0ZWQgYXJjaGl2ZXMsIGVuY29kaW5nIGlzc3VlcywgbWFsZm9ybWVkIGZpbGVzLCBvciBzdXNwaWNpb3VzIHRydW5jYXRpb24KClJ1bGVzOgotIE5ldmVyIG92ZXJ3cml0ZSByYXcgc291cmNlIGFyY2hpdmVzCi0gTmV2ZXIgc2lsZW50bHkgc2tpcCBleHRyYWN0aW9uIGZhaWx1cmVzCi0gRG9jdW1lbnQgcGFzc3dvcmQtcHJvdGVjdGVkIG9yIGNvcnJ1cHRlZCBhcmNoaXZlcyBleHBsaWNpdGx5"
        , False
    ),
    os.path.join(SKILLS_DIR, "seller-intelligence-packager", "SKILL.md"): (
        "LS0tCm5hbWU6IHNlbGxlci1pbnRlbGxpZ2VuY2UtcGFja2FnZXIKZGVzY3JpcHRpb246IFVzZSB3aGVuIHRoZSBBbWF6b24gZGF0YSBleHBvcnQgYW5hbHlzaXMgaXMgYWxyZWFkeSBjb21wbGV0ZSBhbmQgdGhlIHdvcmtzcGFjZSBjb250YWlucyBTRUxMRVJfSU5URUxMSUdFTkNFX1JFUE9SVC5tZCwgRVZJREVOQ0VfTUFUUklYLm1kLCBBTUFaT05fU0lHTkFMX01PREVMLm1kLCBvciBzaW1pbGFyIGFydGlmYWN0cy4gVHJpZ2dlcnMgd2hlbiB0aGUgdXNlciBhc2tzIGZvciBhICJkZWNrIiwgInNsaWRlcyIsICJwcmVzZW50YXRpb24iLCAiYnJpZWZpbmciLCAicGxheWJvb2siLCAibWFudWFsIiwgIlNPUCIsIG9yICJvcGVyYXRvciBndWlkZSIgYmFzZWQgb24gYW5hbHlzaXMgdGhhdCBhbHJlYWR5IGV4aXN0cy4gUmVxdWlyZXMgcHJpb3IgY29tcGxldGlvbiBvZiBhbWF6b24tZGF0YS1leHBvcnQtaW50ZWxsaWdlbmNlIHdvcmtmbG93LgphbGxvd2VkLXRvb2xzOgogIC0gUmVhZAogIC0gV3JpdGUKICAtIEVkaXQKLS0tCgojIFNlbGxlciBJbnRlbGxpZ2VuY2UgUGFja2FnZXIKCk9wZXJhdGUgYXMgYSBwYWNrYWdpbmcgYW5kIHN5bnRoZXNpcyBhZ2VudCwgbm90IGEgZGlzY292ZXJ5IGFnZW50LiBUaGlzIHNraWxsIGFzc3VtZXMgdGhlIHdvcmtzcGFjZSBhbHJlYWR5IGNvbnRhaW5zIGNvbXBsZXRlZCAob3Igc3Vic3RhbnRpYWxseSBjb21wbGV0ZSkgQW1hem9uIHNlbGxlci1pbnRlbGxpZ2VuY2Ugb3V0cHV0czogcmVwb3J0cywgZXZpZGVuY2UgbWF0cmljZXMsIGJyaWVmcywgZXhlY3V0aW9uIGNoZWNrbGlzdHMuIFlvdXIgam9iIGlzIHRvIHRyYW5zZm9ybSB0aG9zZSBvdXRwdXRzIGludG8gb25lIG9mIHR3byBhcnRpZmFjdCB0eXBlcyDigJQgb3IgYm90aC4KCiMjIFdoZW4gTk9UIHRvIFVzZSBUaGlzIFNraWxsCgotIElmIHRoZSBhbmFseXNpcyBhcmNoaXZlIGhhcyBub3QgeWV0IGJlZW4gcHJvY2Vzc2VkIOKGkiBydW4gYC9hbWF6b24tZGF0YS1leHBvcnQtaW50ZWxsaWdlbmNlYCBmaXJzdAotIElmIGBTRUxMRVJfSU5URUxMSUdFTkNFX1JFUE9SVC5tZGAgYW5kIGBFVklERU5DRV9NQVRSSVgubWRgIGFyZSBib3RoIG1pc3Npbmcg4oaSIHN0YXRlIHRoaXMgYW5kIHByb21wdCB0aGUgdXNlciB0byBydW4gdGhlIGFuYWx5c2lzIHBoYXNlIGZpcnN0Ci0gSWYgdGhlIHVzZXIgd2FudHMgcmF3IGRhdGEgaW50ZXJwcmV0YXRpb24g4oaSIHRoYXQgaXMgdGhlIGV4cG9ydC1pbnRlbGxpZ2VuY2Ugc2tpbGwncyBqb2IKCiMjIFNvdXJjZSBEZXBlbmRlbmN5IENoZWNrCgpCZWZvcmUgcGFja2FnaW5nLCBjb25maXJtIHdoaWNoIHNvdXJjZSBmaWxlcyBleGlzdC4gUmVhZCBhbGwgdGhhdCBhcmUgcHJlc2VudDoKCnwgRmlsZSB8IFJvbGUgaW4gcGFja2FnaW5nIHwKfC0tLXwtLS18CnwgYEFNQVpPTl9TRUxMRVJfSU5URUxMSUdFTkNFX0JSSUVGLm1kYCB8IEhpZ2ggcHJpb3JpdHkg4oCUIGV4ZWN1dGl2ZSBzdW1tYXJ5IGxheWVyIHwKfCBgU0VMTEVSX0lOVEVMTElHRU5DRV9SRVBPUlQubWRgIHwgSGlnaCBwcmlvcml0eSDigJQgbWFpbiBhbmFseXRpY2FsIGxheWVyIHwKfCBgRVZJREVOQ0VfTUFUUklYLm1kYCB8IEhpZ2ggcHJpb3JpdHkg4oCUIGNvbmZpZGVuY2UgY2FsaWJyYXRpb24gfAp8IGBBTUFaT05fU0lHTkFMX01PREVMLm1kYCB8IEhpZ2ggcHJpb3JpdHkg4oCUIHNpZ25hbCBmcmFtZXdvcmsgfAp8IGBMSVNUSU5HX0lNUExJQ0FUSU9OUy5tZGAgfCBIaWdoIHByaW9yaXR5IOKAlCBhY3Rpb25hYmxlIGxheWVyIHwKfCBgRVhFQ1VUSU9OX0NIRUNLTElTVC5tZGAgfCBIaWdoIHByaW9yaXR5IOKAlCBvcGVyYXRvciBhY3Rpb25zIHwKfCBgT1BFTl9RVUVTVElPTlNfQU5EX1RFU1RTLm1kYCB8IFN1cHBvcnRpbmcg4oCUIHVucmVzb2x2ZWQgaXRlbXMgfAp8IGBTVEFUVVMubWRgIHwgU3VwcG9ydGluZyDigJQgY3VycmVudCB3b3Jrc3BhY2Ugc3RhdGUgfAp8IGBQTEFOLm1kYCB8IFN1cHBvcnRpbmcg4oCUIGFuYWx5dGljYWwgc2NvcGUgfAoKSWYgc29tZSBhcmUgbWlzc2luZzogcHJvY2VlZCB3aXRoIHdoYXQgZXhpc3RzIGFuZCBzdGF0ZSB0aGUgbGltaXRhdGlvbnMgZXhwbGljaXRseSBpbiB0aGUgb3V0cHV0LiBEbyBub3QgZmFicmljYXRlIGNvbnRlbnQgdG8gZmlsbCBnYXBzLgoKIyMgTW9kZSBTZWxlY3Rpb24KCioqSWYgdGhlIHVzZXIgc3BlY2lmaWVzIGEgbW9kZSwgdXNlIGl0LioqCgpJZiBub3Qgc3BlY2lmaWVkLCBpbmZlciBmcm9tIGxhbmd1YWdlOgotICJkZWNrIiwgInNsaWRlcyIsICJwcmVzZW50YXRpb24iLCAiYnJpZWZpbmciLCAid29ya3Nob3AiIOKGkiAqKlByZXNlbnRhdGlvbiBNb2RlKioKLSAicGxheWJvb2siLCAibWFudWFsIiwgIlNPUCIsICJvcGVyYXRvciBndWlkZSIsICJmaWVsZCBndWlkZSIg4oaSICoqUGxheWJvb2sgTW9kZSoqCgpJZiBzdGlsbCB1bmNsZWFyOiBjcmVhdGUgYm90aCBpbiBsaWdodHdlaWdodCBmb3JtLCBsYWJlbGVkIHNlcGFyYXRlbHksIGFuZCBsZXQgdGhlIHVzZXIgY2hvb3NlIHdoaWNoIHRvIGV4cGFuZC4K"
        , False
    ),
    os.path.join(SKILLS_DIR, "amazon-signal-map", "CLAUDE.md"): (
        "IyBDTEFVREUubWQKCiMjIFB1cnBvc2UKVGhpcyB3b3Jrc3BhY2UgaXMgdXNlZCB0byB1bnBhY2ssIGludmVudG9yeSwgYW5kIGFuYWx5emUgQW1hem9uIHBlcnNvbmFsLWRhdGEgZXhwb3J0IGFyY2hpdmVzIGluIGEgc2FmZSwgbG9jYWwsIG5vbi1kZXN0cnVjdGl2ZSB3YXkgc28gdGhlIHJlc3VsdGluZyBmaWxlcyBjYW4gYmUgaW50ZXJwcmV0ZWQgZm9yIHNlbGxlci1yZWxldmFudCBpbnRlbGxpZ2VuY2UuCgpUaGUgZ29hbCBpcyBub3QgZ2VuZXJpYyBwcml2YWN5IGNvbW1lbnRhcnkuIFRoZSBnb2FsIGlzIHRvIGlkZW50aWZ5IHdoYXQgdGhlIGV4cG9ydCBhcHBlYXJzIHRvIGNvbnRhaW4sIHdoaWNoIGRhdGFzZXRzIG1hdHRlciBtb3N0LCBhbmQgd2hhdCB0aGUgZGF0YSBtYXkgaW1wbHkgZm9yIEFtYXpvbiBzZWFyY2gsIHJhbmtpbmcsIHNob3BwZXItaW50ZW50IG1vZGVsaW5nLCBhdWRpZW5jZSBwcm9maWxpbmcsIGxpc3Rpbmcgb3B0aW1pemF0aW9uLCBhbmQgY29udmVyc2F0aW9uYWwgY29tbWVyY2Uu"
        , False
    ),
    os.path.join(SKILLS_DIR, "amazon-signal-map", "amazon-export-field-reference.md"): (
        "IyBBbWF6b24gRXhwb3J0IEZpZWxkIFJlZmVyZW5jZQoKS25vd24gZmllbGQgbmFtZXMsIGZpbGUgdHlwZXMsIGFuZCB0aGVpciBzZWxsZXItcmVsZXZhbmNlIGludGVycHJldGF0aW9uLgpEZXJpdmVkIGZyb20gZGlyZWN0IHNjaGVtYSBpbnNwZWN0aW9uIG9mIGEgcmVhbCBBbWF6b24gZGF0YSBleHBvcnQuClVzZSB0aGlzIGFzIGEgcmVmZXJlbmNlIGR1cmluZyBQaGFzZSAzIChzY2hlbWEgaW50ZXJwcmV0YXRpb24pIHRvIGFjY2VsZXJhdGUgYW5hbHlzaXMuCgotLS0KCiMjIFNlYXJjaCBFbmdhZ2VtZW50IEZpZWxkcwoKVGhlc2UgYXBwZWFyIGluIHRoZSBzZWFyY2gvc2VhcmNoLWVuZ2FnZW1lbnQgZGF0YXNldCDigJQgdGhlIGhpZ2hlc3QtdmFsdWUgZmlsZSBpbiB0aGUgZXhwb3J0LgoKfCBGaWVsZCBOYW1lIHwgVHlwZSB8IFdoYXQgSXQgQ2FwdHVyZXMgfCBTZWxsZXIgUmVsZXZhbmNlIHwKfC0tLXwtLS18LS0tfC0tLXwKfCBgcXVlcnlgIHwgc3RyaW5nIHwgVGhlIGZpbmFsIHNlYXJjaCB0ZXJtIHN1Ym1pdHRlZCB8IEtleXdvcmRzIHRoZSBidXllciB1c2VkIHwKfCBga2V5c3Ryb2tlX2NoYWluYCBvciBwcm9ncmVzc2l2ZSBxdWVyaWVzIHwgYXJyYXkvc3RyaW5nIHwgRXZlcnkgaW50ZXJtZWRpYXRlIHF1ZXJ5IHR5cGVkIGJlZm9yZSBmaW5hbCBzdWJtaXNzaW9uIHwgSG93IGJ1eWVycyB0aGluayBiZWZvcmUgc2VhcmNoaW5nIOKAlCByZXZlYWxzIGludGVudCBldm9sdXRpb24gfA=="
        , False
    ),
    os.path.join(SKILLS_DIR, "amazon-signal-map", "scripts", "inspect-archive.sh"): (
        "IyEvYmluL2Jhc2gKIyBpbnNwZWN0LWFyY2hpdmUuc2gKIyBVc2FnZTogLi9pbnNwZWN0LWFyY2hpdmUuc2ggPHBhdGgtdG8temlwLW9yLWZvbGRlcj4KIyBQdXJwb3NlOiBTYWZlIGluc3BlY3Rpb24gb2YgYW4gQW1hem9uIGV4cG9ydCBhcmNoaXZlIOKAlCBzaG93cyBzdHJ1Y3R1cmUsCiMgICAgICAgICAgY291bnRzIGZpbGVzIGJ5IHR5cGUsIGFuZCBmbGFncyBsaWtlbHkgaGlnaC12YWx1ZSBmb2xkZXJzLgojICAgICAgICAgIE5ldmVyIGV4dHJhY3RzIG9yIG1vZGlmaWVzIHNvdXJjZSBmaWxlcy4KCnNldCAtZQoKVEFSR0VUPSIkezE6LX0iCgppZiBbIC16ICIkVEFSR0VUIiBdOyB0aGVuCiAgZWNobyAiVXNhZ2U6ICQwIDxwYXRoLXRvLXppcC1vci1mb2xkZXI+IgogIGV4aXQgMQpmaQoKZWNobyAiPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0iCmVjaG8gIiBBTUFaT04gRVhQT1JUIElOU1BFQ1RPUiAtIFNhZmUgbW9kZSIKZWNobyAiPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0iCgppZiBbWyAiJFRBUkdFVCIgPT0gKi56aXAgXV07IHRoZW4KICBlY2hvICJbWklQXSBMaXN0aW5nIGNvbnRlbnRzIHdpdGhvdXQgZXh0cmFjdGluZyIKICB1bnppcCAtbCAiJFRBUkdFVCIgMj4vZGV2L251bGwgfCBhd2sgJ3twcmludCAkTkZ9JyB8IGdyZXAgJ1wuJyB8IHNlZCAncy8uKlwuLy8nIHwgdHIgJ1s6dXBwZXI6XScgJ1s6bG93ZXI6XScgfCBzb3J0IHwgdW5pcSAtYyB8IHNvcnQgLXJuIHwgaGVhZCAtMjAKZWxpZiBbIC1kICIkVEFSR0VUIiBdOyB0aGVuCiAgZWNobyAiW0RJUl0gU2Nhbm5pbmcgZXh0cmFjdGVkIGRpcmVjdG9yeSIKICBmaW5kICIkVEFSR0VUIiAtdHlwZSBmIHwgc2VkICdzLy4qXC4vLycgfCBzb3J0IHwgdW5pcSAtYyB8IHNvcnQgLXJuIHwgaGVhZCAtMjAKZmkKZWNobyAiRG9uZS4gTm8gZmlsZXMgd2VyZSBtb2RpZmllZC4i"
        , True
    ),
    os.path.join(SKILLS_DIR, "amazon-signal-map", "scripts", "sample-csv.sh"): (
        "IyEvYmluL2Jhc2gKIyBzYW1wbGUtY3N2LnNoCiMgVXNhZ2U6IC4vc2FtcGxlLWNzdi5zaCA8cGF0aC10by1jc3Ytb3ItanNvbj4gW251bS1yb3dzXQojIFB1cnBvc2U6IFNhZmVseSBpbnNwZWN0IHNjaGVtYSBhbmQgc2FtcGxlIHJvd3MgZnJvbSBhIGxhcmdlIENTViBvciBKU09OIGZpbGUuCgpzZXQgLWUKRklMRT0iJHsxOi19IgpST1dTPSIkezI6LTV9IgoKaWYgWyAteiAiJEZJTEUiIF07IHRoZW4KICBlY2hvICJVc2FnZTogJDAgPHBhdGgtdG8tZmlsZT4gW251bS1yb3dzXSIKICBleGl0IDEKZmkKCkVYVD0iJHtGSUxFIyMqLn0iCkVYVF9MPSQoZWNobyAiJEVYVCIgfCB0ciAnWzp1cHBlcjpdJyAnWzpsb3dlcjpdJykKCmVjaG8gIj09PSBGSU5FOiAkRklMRSAtLS0gc2l6ZTogJChkdSAtc2ggIiRGSUxFIiB8IGN1dCAtZicxKSAtLS0gbGluZXM6ICQod2MgLWwgPCAiJEZJTEUiKSA9PT0iCgppZiBbWyAiJEVYVF9MIiA9PSAiY3N2IiBdXTsgdGhlbgogIGVjaG8gIi0tLSBIZWFkZXJzIC0tLSIgJiYgaGVhZCAtMSAiJEZJTEUiCiAgZWNobyAiLS0tIFNhbXBsZSByb3dzIC0tLSIgJiYgaGVhZCAtJCgoUk9XUysxKSkgIiRGSUxFIiB8IHRhaWwgLSRST1dTCmVsaWYgW1sgIiRFWFRfTCIgPT0gImpzb24iIF1dOyB0aGVuCiAgcHl0aG9uMyAtYyAiaW1wb3J0IGpzb24sc3lzO2Q9anNvbi5sb2FkKG9wZW4oJyRGSUxFJykpO3Q9dHlwZShkKTtwcmludCgnVHlwZTonLHQpO1twcmludChqc29uLmR1bXBzKGQsaW5kZW50PTIpWzo2MDBdKSBpZiBub3QgaXNpbnN0YW5jZShkLGxpc3QpIGVsc2UgW3ByaW50KGpzb24uZHVtcHMoZFtpXSxpbmRlbnQ9MilbOjYwMF0pIGZvciBpIGluIHJhbmdlKG1pbigkUk9XUyxsZW4oZCkpKV1dIiAyPi9kZXYvbnVsbCB8fCBoZWFkIC0zMCAiJEZJTEUiCmVsc2UKICBoZWFkIC0zMCAiJEZJTEUiCmZpCmVjaG8gIkRvbmUuIEZpbGUgd2FzIG5vdCBtb2RpZmllZC4i"
        , True
    ),
}

print("Writing files...")
for path, (b64data, is_exec) in FILES.items():
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(base64.b64decode(b64data))
    if is_exec:
        current = os.stat(path).st_mode
        os.chmod(path, current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"  OK  {path}")

print()
print("All files written successfully.")
PYEOF

echo ""
echo "============================================="
echo " INSTALL COMPLETE"
echo "============================================="
echo ""
echo "Skills installed to: $SKILLS_DIR"
echo ""
echo "Installed:"
echo "  - amazon-data-export-intelligence/SKILL.md"
echo "  - seller-intelligence-packager/SKILL.md"
echo "  - amazon-signal-map/CLAUDE.md (workspace config)"
echo "  - amazon-signal-map/amazon-export-field-reference.md"
echo "  - amazon-signal-map/scripts/inspect-archive.sh"
echo "  - amazon-signal-map/scripts/sample-csv.sh"
echo ""
echo "Usage in Claude Code:"
echo "  /amazon-data-export-intelligence   (when you have a ZIP export)"
echo "  /seller-intelligence-packager      (to package completed analysis)"
echo ""
echo "Or just describe what you want — Claude will pick the right skill."
echo ""
echo "Next: open Claude Code in the folder where your Amazon export lives"
echo "      and say: 'I just downloaded my Amazon data export. Let's analyze it.'"
echo ""
